### ISSUE TITLE
Instant OCAT crash

### ISSUE THREAD

**Issue by unqltango** [GPUOpen-Tools/OCAT#54]
I just downloaded OCAT and installed it. The install went w/o any problem. When I try to start it, it crashes at once. 

https://imgur.com/OVTxpU0

I did not find any information about required Op system. I tried on:

W7 Professional 64 
.net FW 4.7.2
GTX 1080Ti, latest driver (actually I just put this in my computer, and wanted to capture some Vulkan gameplay from X4: Foundations)

**Comment by aurolou** [comment]
Thanks for the report. I could repro the issue on a Win7 system. Looking for a solution now :)

**Comment by aurolou** [comment]
Could you please try out this [version](https://ci.appveyor.com/api/buildjobs/m8s1w9gpo39y5udm/artifacts/OCAT_1.3.0.197.exe)? OCAT should be able to start successfully on a Win7 system. Please let me know if it works for you.

**Comment by unqltango** [comment]
Hi, sorry for the slow response. I can't even install this version.

[https://imgur.com/a/ZQBZ57V](url)

Log:

[1C40:1C50][2019-01-12T12:29:56]i001: Burn v3.11.0.1701, Windows v6.1 (Build 7601: Service Pack 1), path: C:\Users\Username\AppData\Local\Temp\{8738973D-E611-4EE5-B57C-BDD74474BB22}\.cr\OCAT_1.3.0.197.exe
[1C40:1C50][2019-01-12T12:29:56]i000: Initializing string variable 'InstallFolder' to value '[ProgramFilesFolder]OCAT'
[1C40:1C50][2019-01-12T12:29:56]i009: Command Line: '-burn.clean.room=E:\Install\Multimedia\OCAT\OCAT_1.3.0.197.exe -burn.filehandle.attached=196 -burn.filehandle.self=204'
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'WixBundleOriginalSource' to value 'E:\Install\Multimedia\OCAT\OCAT_1.3.0.197.exe'
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'E:\Install\Multimedia\OCAT\'
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Username\AppData\Local\Temp\Open_Capture_and_Analytics_Tool_(OCAT)_20190112122956.log'
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'WixBundleName' to value 'Open Capture and Analytics Tool (OCAT)'
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'WixBundleManufacturer' to value 'Advanced Micro Devices, Inc.'
[1C40:15A4][2019-01-12T12:29:56]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[1C40:15A4][2019-01-12T12:29:56]i000: Setting version variable 'WixBundleFileVersion' to value '1.3.0.197'
[1C40:1C50][2019-01-12T12:29:56]i100: Detect begin, 3 packages
[1C40:1C50][2019-01-12T12:29:56]i000: Setting string variable 'NETFRAMEWORK45' to value '461814'
[1C40:1C50][2019-01-12T12:29:56]i102: Detected related bundle: {56ab0a3f-8818-4086-9206-002aa6695edb}, type: Upgrade, scope: PerMachine, version: 1.3.0.189, operation: MajorUpgrade
[1C40:1C50][2019-01-12T12:29:56]i052: Condition 'NETFRAMEWORK45 >= 379893' evaluates to true.
[1C40:1C50][2019-01-12T12:29:56]i103: Detected related package: {9023EFE9-A7E5-4604-81D5-ED94A02DFEDF}, scope: PerMachine, version: 1.3.0.189, language: 0 operation: MajorUpgrade
[1C40:1C50][2019-01-12T12:29:56]i101: Detected package: NetFx452Web, state: Present, cached: None
[1C40:1C50][2019-01-12T12:29:56]i101: Detected package: vc_redist.x64.exe, state: Absent, cached: None
[1C40:1C50][2019-01-12T12:29:56]i101: Detected package: OCATPackage, state: Absent, cached: None
[1C40:1C50][2019-01-12T12:29:56]i199: Detect complete, result: 0x0
[1C40:15A4][2019-01-12T12:29:59]i000: Setting numeric variable 'EulaAcceptCheckbox' to value 1
[1C40:1C50][2019-01-12T12:29:59]i200: Plan begin, 3 packages, action: Install
[1C40:1C50][2019-01-12T12:29:59]w321: Skipping dependency registration on package with no dependency providers: NetFx452Web
[1C40:1C50][2019-01-12T12:29:59]w321: Skipping dependency registration on package with no dependency providers: vc_redist.x64.exe
[1C40:1C50][2019-01-12T12:29:59]i000: Setting string variable 'WixBundleLog_vc_redist.x64.exe' to value 'C:\Users\Username\AppData\Local\Temp\Open_Capture_and_Analytics_Tool_(OCAT)_20190112122956_000_vc_redist.x64.exe.log'
[1C40:1C50][2019-01-12T12:29:59]i000: Setting string variable 'WixBundleRollbackLog_OCATPackage' to value 'C:\Users\Username\AppData\Local\Temp\Open_Capture_and_Analytics_Tool_(OCAT)_20190112122956_001_OCATPackage_rollback.log'
[1C40:1C50][2019-01-12T12:29:59]i000: Setting string variable 'WixBundleLog_OCATPackage' to value 'C:\Users\Username\AppData\Local\Temp\Open_Capture_and_Analytics_Tool_(OCAT)_20190112122956_001_OCATPackage.log'
[1C40:1C50][2019-01-12T12:29:59]i201: Planned package: NetFx452Web, state: Present, default requested: Present, ba requested: Present, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[1C40:1C50][2019-01-12T12:29:59]i201: Planned package: vc_redist.x64.exe, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: Yes, dependency: None
[1C40:1C50][2019-01-12T12:29:59]i201: Planned package: OCATPackage, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
[1C40:1C50][2019-01-12T12:29:59]i207: Planned related bundle: {56ab0a3f-8818-4086-9206-002aa6695edb}, type: Upgrade, default requested: Absent, ba requested: Absent, execute: Uninstall, rollback: Install, dependency: None
[1C40:1C50][2019-01-12T12:29:59]i299: Plan complete, result: 0x0
[1C40:1C50][2019-01-12T12:29:59]i300: Apply begin
[1C40:1C50][2019-01-12T12:29:59]i010: Launching elevated engine process.
[1C40:1C50][2019-01-12T12:30:15]i011: Launched elevated engine process.
[1C40:1C50][2019-01-12T12:30:15]e000: Error 0x800700e8: Failed to wait for child to connect to pipe.
[1C40:1C50][2019-01-12T12:30:15]e000: Error 0x800700e8: Failed to connect to elevated child process.
[1C40:1C50][2019-01-12T12:30:15]e000: Error 0x800700e8: Failed to actually elevate.
[1C40:1C50][2019-01-12T12:30:15]e000: Error 0x800700e8: Failed to elevate.
[1C40:1C50][2019-01-12T12:30:16]i399: Apply complete, result: 0x800700e8, restart: None, ba requested restart:  No

**Comment by Zero3K** [comment]
Here's a log of the crash I am having when using the linked version:

`Application: OCAT.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at Frontend.MainWindow.OnSourceInitialized(System.EventArgs)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Frontend.App.Main()`

**Comment by Zero3K** [comment]
I got it to work by recompiling the latest source of the dev branch.
